# Generated by Django 4.0.5 on 2022-06-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commune', models.CharField(max_length=250)),
                ('maire', models.CharField(max_length=500)),
                ('telephone1', models.CharField(max_length=50)),
                ('telephone2', models.CharField(max_length=50)),
                ('adresse', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('site', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
            ],
            options={
                'db_table': 'str_mairie',
            },
        ),
    ]
