# Generated by Django 4.0.5 on 2022-06-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtatCivil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mariage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.IntegerField(choices=[('acte_mariage', 'ACTE DE MARIAGE')], verbose_name='Type de Document')),
                ('numero', models.CharField(max_length=5, unique=True)),
                ('requerant1', models.CharField(max_length=500, verbose_name='Nom et Prenoms du Marie(e)')),
                ('profession_req1', models.CharField(max_length=500, verbose_name='Profession du Marie(e)')),
                ('domicile_req1', models.CharField(max_length=500, verbose_name='Lieu de Domicile du Marie(e)')),
                ('date_req1', models.DateField(verbose_name='Date de Naissance du Marie(e)')),
                ('lieu_naiss_req1', models.CharField(max_length=500, verbose_name='Lieu de Naissance du Marie(e)')),
                ('pere_req1', models.CharField(max_length=250, verbose_name='Nom et Prénoms du Pere du Marie(e)')),
                ('mere_req1', models.CharField(max_length=250, verbose_name='Nom et Prénoms de la Mere du Marie(e)')),
                ('temoin_req1', models.CharField(max_length=250, verbose_name='Nom et Prénoms du Témoin du Marie(e)')),
                ('tel_temoin_req1', models.CharField(max_length=250, verbose_name='Contact Temoin du Marie(e)')),
                ('profession_temoin_req1', models.CharField(max_length=250, verbose_name='Profession du Temoin du Marie(e)')),
                ('conjoint', models.CharField(choices=[('epoux(se)', 'EPOUX(se)'), ('conjoint(e)', 'CONJOINT(E)')], max_length=150, verbose_name='CONJOINT(E)')),
                ('requerant2', models.CharField(max_length=500, verbose_name='Nom et Prenoms du CONJOINT(E)')),
                ('profession_req2', models.CharField(max_length=500, verbose_name='Profession du CONJOINT(E)')),
                ('domicile_req2', models.CharField(max_length=500, verbose_name='Lieu de Domicile du CONJOINT(E)')),
                ('date_req2', models.DateField(verbose_name='Date de Naissance du CONJOINT(E)')),
                ('lieu_naiss_req2', models.CharField(max_length=500, verbose_name='Lieu de Naissance du CONJOINT(E)')),
                ('pere_req2', models.CharField(max_length=250, verbose_name='Nom et Prénoms du Pere duCONJOINT(E)')),
                ('mere_req2', models.CharField(max_length=250, verbose_name='Nom et Prénoms de la Mere du CONJOINT(E)')),
                ('temoin_req2', models.CharField(max_length=250, verbose_name='Nom et Prénoms du Témoin du CONJOINT(E)')),
                ('tel_temoin_req2', models.CharField(max_length=250, verbose_name='Contact Temoin du CONJOINT(E)')),
                ('profession_temoin_req2', models.CharField(max_length=250, verbose_name='Profession du Temoin du CONJOINT(E)')),
                ('regime', models.CharField(choices=[('simple', 'SIMPLE'), ('communaute', 'COMUAUTE DE BIEN')], max_length=150, verbose_name='Type de Regime')),
                ('date_mariage', models.DateField(verbose_name='Date du Mariage')),
                ('heure_mariage', models.DateField(verbose_name='Heure du Mariage')),
                ('lieu_mariage', models.CharField(max_length=500, verbose_name='Lieu de Celebartion du Mariage')),
            ],
            options={
                'db_table': 'Actes_Mariage',
            },
        ),
        migrations.DeleteModel(
            name='Naissance',
        ),
    ]
