# Generated by Django 4.0.5 on 2022-06-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtatCivil', '0002_mariage_delete_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mariage',
            name='categorie',
            field=models.IntegerField(choices=[('acte_mariage', 'ACTE DE MARIAGE'), ('acte_naissance', 'ACTE DE NAISSANCE')]),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='conjoint',
            field=models.CharField(choices=[('epoux(se)', 'EPOUX(se)'), ('conjoint(e)', 'CONJOINT(E)')], max_length=150),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='date_mariage',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='date_req1',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='date_req2',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='domicile_req1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='domicile_req2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='heure_mariage',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='lieu_mariage',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='lieu_naiss_req1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='lieu_naiss_req2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='mere_req1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='mere_req2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='pere_req1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='pere_req2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='profession_req1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='profession_req2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='profession_temoin_req1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='profession_temoin_req2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='regime',
            field=models.CharField(choices=[('simple', 'SIMPLE'), ('communaute', 'COMUAUTE DE BIEN')], max_length=150),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='requerant1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='requerant2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='tel_temoin_req1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='tel_temoin_req2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='temoin_req1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='temoin_req2',
            field=models.CharField(max_length=250),
        ),
    ]
